// prisma/seed/categories.ts
// ─────────────────────────────────────────────────────────────────────────────
// Medicine category seed data
// Matches: MedicineCategory model (id auto-generated by Prisma @default(uuid()))
// ─────────────────────────────────────────────────────────────────────────────

export const categories = [
  {
    name: 'Tablets & Capsules',
    description: 'Oral solid dosage forms including tablets, capsules, and caplets',
  },
  {
    name: 'Syrups & Suspensions',
    description: 'Liquid oral medicines including syrups, suspensions, and drops',
  },
  {
    name: 'Injections & IV Fluids',
    description: 'Parenteral medicines including injections, infusions, and IV solutions',
  },
  {
    name: 'Topical & Skin Care',
    description: 'Creams, ointments, gels, and lotions for external use',
  },
  {
    name: 'Eye & Ear Drops',
    description: 'Ophthalmic and otic preparations',
  },
  {
    name: 'Vitamins & Supplements',
    description: 'Nutritional supplements, vitamins, minerals, and health boosters',
  },
  {
    name: 'Antacids & Digestive',
    description: 'Medicines for acidity, indigestion, constipation, and digestive disorders',
  },
  {
    name: 'Respiratory & Allergy',
    description: 'Medicines for asthma, cold, cough, and allergic conditions',
  },
  {
    name: 'Antibiotics',
    description: 'Prescription-only antibacterial and antimicrobial agents',
  },
  {
    name: 'Diabetes Care',
    description: 'Blood glucose control medicines, insulin, and diabetic monitoring supplies',
  },
  {
    name: 'Cardiac & Blood Pressure',
    description: 'Medicines for heart conditions, hypertension, and cholesterol management',
  },
  {
    name: 'Pain & Fever Relief',
    description: 'Analgesics, antipyretics, and anti-inflammatory medicines',
  },
];